export enum ProfileJobRole {
  DESIGN_ENGINEER = 'DESIGN_ENGINEER',
  PURCHASING_ENGINEER = 'PURCHASING_ENGINEER',
  CONTRACT_MANUFACTURER = 'CONTRACT_MANUFACTURER',
  ELECTRONIC_MANUFACTURING_SERVICE = 'ELECTRONIC_MANUFACTURING_SERVICE',
}
